name: Python CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name : Install Test Dependencies
      run: pip install -r requirements-dev.txt

    - name: Run Tests
      run: |
        python -m unittest ntp_amplification_test.py
      continue-on-error: true

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Linter
      run: pre-commit install

    - name: Lint Code
      run: pre-commit run --all-files
